### ISSUE TITLE
Rename dockerhub account, or fix name in readme

### ISSUE THREAD

**Issue by SpangleLabs** [nwalke/tautulli-exporter#2]
Have you considered pushing the docker image to dockerhub, or ghcr.io? Would make it easier to use, rather than having to clone the repo and build the docker image

**Comment by SpangleLabs** [comment]
Ah, spotted the penultimate commit here, and realised it's on dockerhub under your old username.

**Comment by nwalke** [comment]
I realize this is incredibly not ideal, but I cannot change my username on Dockerhub and probably will be creating a new account over there.  With over a million pulls I think I'm about to give some people a bad day, but...   eek.

**Comment by nwalke** [comment]
Available at the name specified in the README now.

**Comment by nwalke** [comment]
Edited your comment to remove the links to the previous username.
